services:
  db:
    container_name: rmutt_db
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432" 
    volumes:
      - vutf_db_data:/var/lib/postgresql/data

  redis:
    container_name: rmutt_redis
    image: redis:7
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - vutf_redis_data:/data

  adminer:
    container_name: rmutt_adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  vutf_db_data:
  vutf_redis_data:
